fail_fast: true
exclude: ^(notebooks/|scripts/|.github/|docs/|dev_scripts/|tests/)
repos:
  - repo: local
    hooks:
      - id: install pre-commit
        name: install pre-commit
        entry: python -m pip install -q sphinx==5.1.1 pre-commit recommonmark gitverse
        language: system
        pass_filenames: false
        always_run: true

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: requirements-txt-fixer
      - id: sort-simple-yaml
      - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: 26.5.1
    hooks:
      - id: black
        exclude: docs_gen/

  - repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-docstrings
          - flake8-sfs
        args: [ --max-line-length=120, --extend-ignore=SFS3 D107 SFS301 D100 D104 D401 SFS101 SFS201 D412 ]

  - repo: https://github.com/PyCQA/isort
    rev: 8.0.1
    hooks:
      - id: isort
        args: [ --profile, black ]

  - repo: local
    hooks:
      - id: gitverse
        name: generate release notes
        entry: gitverse-release reverse -f release_notes.rst -t 'Release Notes'
        language: python
        pass_filenames: false
        always_run: true
