[project]
name = "FastAPI-UI-Auth"
dynamic = ["dependencies", "version"]
description = "Python module to add username and password authentication to specific FastAPI routes"
readme = "README.md"
requires-python = ">=3.11"

[tool.setuptools]
packages = ["uiauth", "uiauth.templates"]
[tool.setuptools.package-data]
"uiauth.templates" = ["*.html"]

[tool.setuptools.dynamic]
dependencies = { file = ["requirements.txt"] }
version = { attr = "uiauth.version.version" }

[project.optional-dependencies]
dev = [
    "websockets==15.0.*",
    "pre-commit==4.2.*",
    "uvicorn==0.49.*",
    "qrcode[pil]==8.2.*",
]
test = [
    "pytest",
    "pytest-cov",
    "httpx2",
]

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.coverage.run]
source = ["uiauth"]
omit = ["uiauth/version.py"]

[tool.coverage.report]
show_missing = true

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project.scripts]
uiauth_totp = "uiauth:_totp"
"uiauth-totp" = "uiauth:_totp"

[project.urls]
Homepage = "https://github.com/thevickypedia/FastAPI-UI-Auth"
Source = "https://github.com/thevickypedia/FastAPI-UI-Auth"
"Bug Tracker" = "https://github.com/thevickypedia/FastAPI-UI-Auth/issues"
"Release Notes" = "https://github.com/thevickypedia/FastAPI-UI-Auth/blob/main/release_notes.rst"
