name: pypi-publish

on:
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  run-tests:
    uses: ./.github/workflows/code-coverage.yml

  pypi-publisher:
    needs: run-tests
    runs-on: thevickypedia-default
    steps:
      - uses: thevickypedia/pypi-publisher@v3
        env:
          token: ${{ secrets.PYPI_TOKEN }}

  release-notes:
    needs: pypi-publisher
    runs-on: thevickypedia-default
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: thevickypedia/update-release-notes@v2
        env:
          git_token: ${{ secrets.GIT_TOKEN }}
